[package]
name = "pyrkafka"
version = "0.2.0"
edition = "2021"

[lib]
name = "pyrkafka"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24"
rdkafka = { version = "0.36", features = ["cmake-build", "ssl-vendored", "gssapi-vendored", "libz-static", "zstd"] }